# Generated by Django 5.2.7 on 2025-10-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_no', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('uploaded_file', models.FileField(help_text='Upload PDF, JPG, DOC files', upload_to='uploads/%Y/%m/%d/', verbose_name='File Upload')),
                ('name_size', models.FloatField(default=0, verbose_name='Name Size (KB)')),
                ('email_size', models.FloatField(default=0, verbose_name='Email Size (KB)')),
                ('phone_no_size', models.FloatField(default=0, verbose_name='Phone Size (KB)')),
                ('file_size', models.FloatField(default=0, verbose_name='File Size (KB)')),
                ('total_size', models.FloatField(default=0, verbose_name='Total Size (KB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Data Record',
                'verbose_name_plural': 'Data Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
