# Generated by Django 5.2.7 on 2025-10-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('name_size', models.FloatField(default=0)),
                ('email_size', models.FloatField(default=0)),
                ('phone_size', models.FloatField(default=0)),
                ('file_size', models.FloatField(default=0)),
                ('total_size', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DataRecord',
        ),
    ]
